export const keysCollectionName = process.env.REACT_APP_FIRESTORE_KEYS_COLLECTION_NAME;
export const usersCollectionName = process.env.REACT_APP_FIRESTORE_USERS_COLLECTION_NAME;
export const vaultsCollectionName = process.env.REACT_APP_FIRESTORE_VAULTS_COLLECTION_NAME;
