name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        env:
          REACT_APP_FIREBASE_CONFIG: ${{ secrets.REACT_APP_FIREBASE_CONFIG }}
          REACT_APP_FIRESTORE_KEYS_COLLECTION_NAME: ${{ secrets.REACT_APP_FIRESTORE_KEYS_COLLECTION_NAME }}
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "Shubham Panchal"
          git config --global user.email "panchalshubham0608@gmail.com"

          npx gh-pages -d build -u "Shubham Panchal <panchalshubham0608@gmail.com>" -r https://x-access-token:${GH_TOKEN}@github.com/panchalshubham0608/securekey.git

